language: python
python:
  - 2.7
cache:
  directories:
    - $HOME/.cache/pip
before_script:
  - sudo -- sh -c "echo '127.0.0.1  dukaan.travis.dev' >> /etc/hosts"
  - psql -c 'create database dukaan_testing;' -U postgres
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - ./runtests.sh
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
